### ISSUE TITLE
Allow GHC 8.4

### ISSUE THREAD

**Issue by ndmitchell** [sebastiaanvisser/fclabels#34]
Which has a base higher than you support

**Comment by ndmitchell** [comment]
Someone uses `fc-labels` in the `shake-language-c` package, and I test that in the Shake CI, so currently the Shake CI for GHC 8.4 breaks. I appreciate that some people are keen to avoid hackage releases for unreleased GHC's, but I can't for the life of me think of any reason to follow that approach - you're just cutting down on other people doing beta testing and increasing the chance a released GHC will break with your package. But then I wouldn't put a restrictive base upper bound either...

**Comment by bergmark** [comment]
Sorry, I meant to get back to this sooner!

With `allow-newer` for cabal-install and stack, does it really prevent anyone from using the lib since no haskell sources needed changing? Nevertheless, i published https://hackage.haskell.org/package/fclabels-2.0.3.3

**Comment by ndmitchell** [comment]
My users don't necessarily use allow-newer, and failing to install might mean they give up, so I never rely on allow-newer. Thanks for the fix!

**Comment by hesselink** [comment]
Just to provide some historical context here, I think we used to try and work with unreleased GHC versions, but things tended to break relatively often, sometimes due to changes in base, often due to changes in TH. Maybe things are better now, I saw some conversations about version bumps in core libraries even if they're unreleased.
